---
title: "Reading Readiness"
format: 
  html:
    mainfont: sans-serif
editor: visual
execute:
  echo: false
  warning: false
  message: false
server: shiny
---

```{r}
#| context: data 

library(tidyverse)
library(gt)
library(gtExtras)
library(ggbump)
library(shiny)
library(plotly)
library(bslib)

df <- read_rds("CCRPI_data.rds")

school_list <- df |>
  filter(grade_cluster == 'E',
         school_name != 'All Schools') |> 
  select(school_name) |> 
  distinct() |> 
  arrange(school_name) |> 
  pull()

palette = scico::scico(n = 100, palette = "vik",direction =-1)
palette_rev = scico::scico(n = 100, palette = "vik",direction = 1)

ranked_df <- df |> 
  filter(reporting_label == 'ALL Students',
         school_name != 'All Schools') |> 
  select(school_year,school_name,grade_cluster,indicator_score) |> 
  group_by(school_year,grade_cluster) |> 
  mutate(rank = dense_rank(desc(indicator_score))) |> 
  arrange(school_year,rank) 


avg_ranks <- ranked_df |> 
  group_by(school_name) |> 
  summarise(mean_rank = mean(rank), sd_rank = sd(rank,na.rm = TRUE))
```

> “You will learn most things by looking, but reading gives understanding. Reading will make you free.” ― Paul Rand


```{r}
#| fig-width: 9
#| fig-height: 4
overall_plot <- df |> 
  filter(school_name == 'All Schools', reporting_label == 'ALL Students', grade_cluster == 'E') |> 
  select(school_year, indicator_score) |> 
  mutate(
    indicator_score = as.numeric(indicator_score)/100,
    tooltip_text = paste0(
      'Year: ',school_year, "\nReading Readiness Proportion: ",
      scales::percent(indicator_score, accuracy = 0.1)
    )
  ) |> 
  ggplot(aes(x = school_year, y = indicator_score, group = 1, text = tooltip_text)) +
  geom_line(linewidth = 1) +
  geom_point(size = 3) +
  scale_y_continuous(label = scales::percent_format(accuracy = 1)) +
  labs(x = NULL,
       title = 'Reading Readiness Scores Across All Coweta County Elementary Schools') +
  theme_minimal() +
  theme(
    text = element_text(family = "sans"),
    legend.position = 'top',
    legend.text = element_text(size = 6),
    axis.text = element_text(face = 'bold', size = 11, color = 'black'),
    plot.title = ggtext::element_textbox_simple(face = 'bold', color = 'black', size = 15),
    plot.title.position = 'plot',
    axis.line = element_blank(),        
    axis.ticks.y = element_blank(),      
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank()
  )
  
ggplotly(overall_plot, tooltip = "text") |> 
  config(displayModeBar = FALSE)
```




```{r}
#| column: screen-inset

ranked_df |> 
  ungroup() |> 
  filter(grade_cluster == 'E') |> 
  select(-c(grade_cluster, rank)) |> 
  mutate(indicator_score = as.numeric(indicator_score),
         indicator_score = indicator_score / 100) |> 
  pivot_wider(names_from = school_year, values_from = indicator_score) |> 
  arrange(school_name) |> 
  left_join(avg_ranks, by = 'school_name') |> 
  mutate(
    change_1yr = `2025` - `2024`,
    change_3yr = `2025` - `2022`,
    change_6yr = `2025` - `2019`,
    covid_gap = `2021` - `2019`
  ) |> 
  select(1:8, change_1yr, change_3yr, change_6yr, covid_gap, everything()) |> 
  arrange(mean_rank) |> 
  gt() |> 
  tab_header(
    title = md("**Table 1: Coweta County Reading Readiness Proportions from 2018 to 2025**"),
    subtitle = "Showing results and comparative analysis for all Elementary Schools in Coweta County"
  ) |> 
  tab_spanner(
    label = md("**CCRPI Annual Scores**"),
    columns = 2:8,
    id = "annual"
  ) |> 
  tab_spanner(
    label = md("**Change Over Time**"),
    columns = 9:12,
    id = "change"
  ) |> 
  tab_spanner(
    label = md("**Rankings**"),
    columns = 13:14,
    id = "rankings"
  ) |> 
  tab_footnote(
    footnote = "Percentage of students at or above grade level on the CCRPI assessments.",
    locations = cells_column_spanners(spanners = "annual")
  ) |> 
  tab_footnote(
    footnote = "Percentage point change from baseline year to 2025.",
    locations = cells_column_spanners(spanners = "change")
  ) |> 
  tab_footnote(
    footnote = "Performance change during COVID-19 pandemic (2019 to 2021). Data for 2020 are missing since assessments were not completed during the pandemic. This measure show the gap between 2019 and 2020.",
    locations = cells_column_labels(columns = covid_gap)
  ) |> 
  tab_footnote(
    footnote = "Average ranking across all years (lower is better)",
    locations = cells_column_spanners(spanners = "rankings")
  ) |> 
  cols_width(
    1 ~ px(280)
  ) |> 
  cols_align(columns = 2:14, align = 'center') |> 
  fmt_percent(2:8) |> 
  fmt_percent(9:12, decimals = 1, force_sign = TRUE) |> 
  fmt_number(13:14) |> 
  data_color(
    columns = 2:8,
    palette = palette,
    domain = c(0, 1)
  ) |>
  data_color(
    columns = mean_rank,
    palette = palette_rev,
    domain = c(1, 19)
  ) |>
  tab_style(
    style = cell_fill(color = "#a8c0d3"),
    locations = cells_body(
      columns = change_1yr,
      rows = change_1yr > 0.15
    )
  ) |>
  tab_style(
    style = cell_fill(color = "#a8c0d3"),
    locations = cells_body(
      columns = change_3yr,
      rows = change_3yr > 0.15
    )
  ) |>
  tab_style(
    style = cell_fill(color = "#a8c0d3"),
    locations = cells_body(
      columns = change_6yr,
      rows = change_6yr > 0.15
    )
  ) |>
  tab_style(
    style = cell_fill(color = "#a8c0d3"),
    locations = cells_body(
      columns = covid_gap,
      rows = covid_gap > 0.15
    )
  ) |>
  tab_style(
    style = cell_fill(color = "lightcoral"),
    locations = cells_body(
      columns = change_1yr,
      rows = change_1yr < -0.15
    )
  ) |>
  tab_style(
    style = cell_fill(color = "lightcoral"),
    locations = cells_body(
      columns = change_3yr,
      rows = change_3yr < -0.15
    )
  ) |>
  tab_style(
    style = cell_fill(color = "lightcoral"),
    locations = cells_body(
      columns = change_6yr,
      rows = change_6yr < -0.15
    )
  ) |>
  tab_style(
    style = cell_fill(color = "lightcoral"),
    locations = cells_body(
      columns = covid_gap,
      rows = covid_gap < -0.15
    )
  ) |> 
  tab_style(
    style = cell_borders(
      sides = "left",
      color = "black",
      weight = px(2)
    ),
    locations = cells_body(columns = c(9, 13))
  ) |> 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_column_labels()
  ) |> 
  tab_options(
    table.font.size = 14,
    heading.align = "left",
    footnotes.font.size = 13,
    table.font.names = "sans"
  ) |> 
  cols_label(school_name = 'School',
             change_1yr = '1 Year Change',
             change_3yr = '3 Year Change',
             change_6yr = '6 Year Change',
             mean_rank = 'Average',
             sd_rank = 'Standard Deviation',
             covid_gap = 'Covid Gap Change') |> 
  opt_interactive(page_size_default = 20)
```


## School Profile

```{css}
#rank_plot {
  border: none !important;
  box-shadow: none !important;
}
```


```{r}
#| column: screen-inset-shaded
div(
  class = "screen-inset-shaded",
  selectInput("school", choices = school_list, label = 'Select a School:'),
  br(),
  layout_columns(
    col_widths = c(6, 6),
    plotlyOutput('rank_plot', width = '100%', height = '500px'),
    plotlyOutput('county_plot', width = '100%', height = '500px')
  )
)
```


```{r}
#| context: server

library(tidyverse)
library(gt)
library(gtExtras)
library(ggbump)
library(shiny)
library(bslib)
library(plotly)

df <- read_rds("CCRPI_data.rds")

plot_bg_color <- '#F8F9FA'
plot_bg_color <- 'white'

output$rank_plot <- renderPlotly({

ranked_df_shiny <- df |>
  filter(reporting_label == 'ALL Students',
         school_name != 'All Schools') |>
  select(school_year, school_name, grade_cluster, indicator_score) |>
  group_by(school_year, grade_cluster) |>
  mutate(rank = dense_rank(desc(indicator_score))) |>
  arrange(school_year, rank) |>
  filter(grade_cluster == 'E') |> 
  mutate(
    selected = ifelse(school_name == input$school, 'Y', 'N'),
    tooltip_text = paste0(
    school_name, "\n",
    "Rank: ", rank, " of 19\n",
    "Score: ", scales::percent(as.numeric(indicator_score)/100, accuracy = 0.1), "\n",
    school_year
    )
  )

ranked_plot <- ranked_df_shiny |> 
  ggplot(aes(x = school_year, y = desc(rank), group = school_name, 
             color = school_name, text = tooltip_text)) +
  geom_bump(
    data = \(x) filter(x, selected == 'N'),
    color = 'gray80',
    alpha = 0.3,
    linewidth = 1
  ) +
  geom_point(
    data = \(x) filter(x, selected == 'N'),
    color = 'gray80',
    alpha = 0.3,
    size = 3
  ) +  
  geom_bump(
    data = \(x) filter(x, selected == 'Y'),
    color = "deepskyblue4",
    linewidth = 1
  ) +
  geom_point(
    data = \(x) filter(x, selected == 'Y'),
    color = "deepskyblue4",
    size = 6
  ) +
  geom_text(
    data = \(x) filter(x, selected == 'Y'),
    aes(label = rank),
    color = 'white',
    size = 3.5,
    fontface = 'bold'
  ) +
  scale_x_discrete(expand = c(0, .4)) +
  theme_minimal() +
  labs(x = NULL,
       y = NULL,
       title = paste0(input$school, " Reading Readiness Scores Ranking from 2018 to 2025"),
       subtitle = 'Rankings are in comparison to all other Elementary Schools in Coweta County') +
  theme(
    text = element_text(family = "sans"),
    legend.position = 'none',
    axis.text = element_text(face = 'bold', size = 11),
    plot.title = ggtext::element_textbox_simple(face = 'bold', color = 'black', size = 15),
    plot.subtitle = ggtext::element_textbox_simple(size = 6),
    plot.title.position = 'plot',
    panel.grid = element_blank(),
    axis.line = element_blank(),        
    axis.text.y = element_blank(),      
    axis.ticks.y = element_blank(),      
    axis.title.y = element_blank()
  )

ggplotly(ranked_plot, tooltip = "text") |> 
  config(displayModeBar = FALSE)

})


output$county_plot <- renderPlotly({
  
county_plot <- df |> 
  filter(school_name %in% c('All Schools', input$school),
         grade_cluster == 'E',
         reporting_label == 'ALL Students') |> 
  mutate(school_name = ifelse(school_name == 'All Schools',
                               'Coweta County Elementary Schools Average',
                               school_name)) |> 
  select(school_year, school_name, reporting_label, indicator_score) |> 
  mutate(indicator_score = as.numeric(indicator_score)/100) |> 
  filter(!is.na(indicator_score)) |> 
  ggplot(aes(x = school_year, 
             y = indicator_score, 
             color = school_name, 
             group = school_name, 
             text = paste0(  
               "<b>", school_name, "</b><br>",
               "Year: ", school_year, "<br>",
               "Score: ", scales::percent(indicator_score, accuracy = 0.1)
             ))) +
  geom_line(linewidth = .8) +
  geom_point(size = 3) +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_minimal() +
  labs(color = NULL,
       x = NULL,
       title = paste0('How do ', input$school, "'s Reading Readiness Scores Compare to all Elementary Schools in Coweta County?"),
       subtitle = 'Chart shows school scores and overall scores by year.') +
  theme(
    text = element_text(family = "sans"),
    legend.position = 'top',
    axis.text = element_text(face = 'bold', size = 11),
    plot.title = ggtext::element_textbox_simple(face = 'bold', color = 'black', size = 15),
    plot.subtitle = ggtext::element_textbox_simple(size = 6),
    plot.title.position = 'plot',
    panel.grid = element_blank(),
    axis.line = element_blank(),        
    axis.text.y = element_blank(),      
    axis.ticks.y = element_blank(),      
    axis.title.y = element_blank()
  )
  
ggplotly(county_plot, tooltip = "text") |> 
  config(displayModeBar = FALSE)
})

```



